### ISSUE TITLE
Definir as funcionalidades da aplicação

### ISSUE THREAD

**Issue by renathaiglesias** [renathaiglesias/pifrontend#1]
Vamos começar a pensar sobre a base do projeto, inicialmente na construção no figma. Lembrando que tudo que for entregue por lá, deverá ser desenvolvido no replit posteriormente. 

Tópicos fundamentais:

- nome do projeto
- cores e tipografia 
- login e cadastro 
- página inicial (estilo app de entrega?)
- pensar na interface fornecedor > catador > cliente

**Comment by DiiegoPaiiva** [comment]
nome do projeto = ReciclaVasco

**Comment by renathaiglesias** [comment]
Lixo tem que ser reciclado mesmo...

**Comment by gabrielduarteds** [comment]
cor: preto e branco

**Comment by DiiegoPaiiva** [comment]
Nome do Projeto = RecyTech, ReciTech, RecyTec, ReciTec, Garizando

**Comment by fillipelipe** [comment]
recicle.com.br
basico, simples, intuitivo, simples para os que não entendem tanto de tecnologia, para esta pesquisando

**Comment by fillipelipe** [comment]
Digamos que eu seja flamenguista, e não entenda muito de internet, e queira entregar algo para reciclar... qual a primeira coisa que ele ira pesquisar ? "onde posso deixar latinha para reciclar?" por exemplo... e pa, recicle.com.br aparece para ele

**Comment by renathaiglesias** [comment]
Então como decidido sábado, o nome **inicial** do projeto será "ReciclApp Brasil". Podendo ser alterado no decorrer do projeto...

Sobre cores, além do Gabriel que sugeriu monocromático, alguma outra paleta sugerida?

**Comment by renathaiglesias** [comment]
Acredito que podemos desenvolver algo semelhante a apps de entrega (ifood, rappi...), mas sem o mapa, apenas uma localização próxima que ligue coletor - coleta - cliente...

**Comment by gabrielduarteds** [comment]
Também precisamos decidir se iremos fazer uma aplicação SPA ou MPA. Quanto a sugestão da paleta de cores, podemos ir decidindo ao longo do projeto.

**Comment by fillipelipe** [comment]
De acordo!

**Comment by gabrielduarteds** [comment]
Como o objetivo do nosso projeto é de conectar catadores de materiais recicláveis aos cidadãos que desejam descartar esses materiais de maneira consciente e sustentável, podemos colocar como principais funcionalidades os seguintes itens:

1 - Cadastro de usuários e catadores: tanto usuários quanto catadores podem se cadastrar no aplicativo de forma simples e gratuita.

2 - Solicitação de coleta: os usuários podem solicitar a coleta de materiais recicláveis, especificando o tipo de material e a quantidade. Essa solicitação é enviada aos catadores cadastrados no aplicativo.

3 - Localização de catadores: o aplicativo mostra a localização dos catadores cadastrados próximos ao usuário, permitindo que ele escolha o catador que realizará a coleta.

4 - Comunicação entre usuários e catadores: o aplicativo possui uma função de chat, que permite que usuários e catadores se comuniquem para acertar detalhes da coleta, como horário e local.
